import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export const revalidate = 0;

export async function GET() {
  const setting = await prisma.setting.findUnique({
    where: { key: 'seo_sitemap_images' }
  });
  const showImages = setting?.value !== 'false';

  const xsl = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
            background-color: #f6f7f7;
          }
          #header {
            background-color: #3b82f6;
            padding: 30px 40px;
            color: #fff;
          }
          #header h1 {
            margin: 0 0 15px 0;
            font-size: 24px;
            font-weight: 600;
          }
          #header p {
            margin: 0;
            font-size: 14px;
            line-height: 1.5;
            color: #e0e7ff;
          }
          #header a {
            color: #fff;
            text-decoration: underline;
          }
          #content {
            padding: 40px;
            max-w-6xl;
            margin: 0 auto;
            background: #fff;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
          }
          .sitemap-info {
            margin-bottom: 20px;
            font-size: 14px;
            color: #4b5563;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
          }
          th {
            background-color: #3b82f6;
            color: white;
            text-align: left;
            padding: 12px 15px;
            font-weight: 600;
          }
          td {
            padding: 12px 15px;
            border-bottom: 1px solid #e5e7eb;
            color: #4b5563;
          }
          tr:nth-child(even) td {
            background-color: #f9fafb;
          }
          tr:hover td {
            background-color: #f3f4f6;
          }
          a {
            color: #3b82f6;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
        </style>
      </head>
      <body>
        <div id="header">
          <h1>XML Sitemap</h1>
          <p>
            This XML Sitemap is generated by Velocity CMS. It is what search engines like Google use to crawl and re-crawl posts/pages/archives on your website.
          </p>
        </div>
        
        <div id="content">
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <div class="sitemap-info">
              This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.
            </div>
            <table>
              <thead>
                <tr>
                  <th>Sitemap</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          
          <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <div class="sitemap-info">
              This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
              <br/><br/>
              <a href="/sitemap_index.xml">&#8592; Sitemap Index</a>
            </div>
            <table>
              <thead>
                <tr>
                  <th>URL</th>
                  ${showImages ? '<th>Images</th>' : ''}
                  <th>Last Mod.</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    ${showImages ? `
                    <td>
                      <xsl:value-of select="count(image:image)"/>
                    </td>` : ''}
                    <td>
                      <xsl:value-of select="concat(substring(sitemap:lastmod, 1, 10), ' ', substring(sitemap:lastmod, 12, 5), ' +00:00')"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

  return new NextResponse(xsl, {
    headers: {
      'Content-Type': 'text/xsl',
    },
  });
}
