import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import TurndownService from 'turndown';

export async function GET(request: Request) {
  // 1. Fetch settings
  const settingsRecords = await prisma.setting.findMany({
    where: {
      key: { in: ['llms_txt_additional_content', 'llms_txt_post_types_posts', 'llms_txt_post_types_pages', 'llms_txt_limit', 'seo_site_title'] }
    }
  });

  const settings = settingsRecords.reduce((acc: any, setting: any) => {
    acc[setting.key] = setting.value;
    return acc;
  }, {});

  // Determine base URL
  const host = request.headers.get('host') || 'localhost:3000';
  const protocol = host.includes('localhost') ? 'http' : 'https';
  const baseUrl = `${protocol}://${host}`;

  const limit = parseInt(settings.llms_txt_limit || '50', 10);

  // 2. Fetch pages if enabled
  const pages = settings.llms_txt_post_types_pages !== 'false' 
    ? await prisma.page.findMany({
        where: { status: 'Published', visibility: 'Public' },
        select: { title: true, slug: true, seoTitle: true, metaDescription: true, contentHtml: true },
        take: limit
      })
    : [];

  // 3. Fetch posts if enabled
  const posts = settings.llms_txt_post_types_posts !== 'false'
    ? await prisma.post.findMany({
        where: { status: 'Published', visibility: 'Public' },
        select: { title: true, slug: true, seoTitle: true, metaDescription: true, contentHtml: true },
        take: limit
      })
    : [];

  const turndownService = new TurndownService({
    headingStyle: 'atx',
    codeBlockStyle: 'fenced'
  });

  const getExcerpt = (html: string | null) => {
    if (!html) return '';
    const text = turndownService.turndown(html).replace(/\r?\n|\r/g, ' ').replace(/\s+/g, ' ').trim();
    if (text.length > 150) {
      return text.substring(0, 147) + '...';
    }
    return text;
  };

  // Build the markdown content
  let content = `Generated by Velocity CMS, this is an llms.txt file designed to help LLMs better understand and index this website.\n\n`;
  
  const siteName = settings.seo_site_title || 'Velocity Consultancy';
  content += `# ${siteName}\n\n`;

  if (settings.llms_txt_additional_content) {
    content += `${settings.llms_txt_additional_content.trim()}\n\n`;
  }

  content += `## Sitemaps\n`;
  content += `[XML Sitemap](${baseUrl}/sitemap_index.xml): Includes all crawlable and indexable pages.\n\n`;

  if (posts.length > 0) {
    content += `## Posts\n`;
    for (const post of posts) {
      content += `- [${post.seoTitle || post.title}](${baseUrl}/${post.slug})`;
      let desc = post.metaDescription ? post.metaDescription.replace(/\r?\n|\r/g, ' ').trim() : getExcerpt(post.contentHtml);
      if (desc) content += `: ${desc}`;
      content += `\n`;
    }
    content += `\n`;
  }

  if (pages.length > 0) {
    content += `## Pages\n`;
    for (const page of pages) {
      content += `- [${page.seoTitle || page.title}](${baseUrl}/${page.slug})`;
      let desc = page.metaDescription ? page.metaDescription.replace(/\r?\n|\r/g, ' ').trim() : getExcerpt(page.contentHtml);
      if (desc) content += `: ${desc}`;
      content += `\n`;
    }
    content += `\n`;
  }

  return new NextResponse(content.trim(), {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400, stale-while-revalidate'
    }
  });
}
